"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CartProvider from "../../CartContext";
import OneSignal from "react-onesignal";
import { useEffect } from "react";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CartProvider>
        <SessionProvider>
          <body className={inter.className}>{children}</body>
        </SessionProvider>
      </CartProvider>
    </html>
  );
}
